primer:
  sequence: ACAATTCATCTTAGTGCCAGACTACTGTACTGTCCCAGAGAATAGACTTGCTTCGTGCGCACCCGTATGCCGCTCGATATGCGTAGCCGTCCATGTTGAT
  max_distance: 5
reverse_primer:
  sequence: TACCA
  max_distance: 2
support: 30
