primer:
  sequence: ATCAACATGGACGGCTACGCATATCGAGCGGCATACGGGTGCGCACGAAGCAAGTCTATTCTCTGGGACAGTACAGTAGTCTGGCACTAAGATGAATTGT
  max_distance: 7
reverse_primer:
  sequence: GGTACC
  max_distance: 2
support: 70
